version: "3.7"

services:
    
    flask:
        build: ./Flask
        container_name: Flask
        restart: always
        environment:
            {APP_NAME=flask-dashboard-app}
    firefox:
        image: jlesage/firefox
        build: ./docker-firefox-master
        ports:
        - "5800:5800"
        - "5000:5000"
        volumes:
        - "/docker/appdata/firefox:/config:rw"

    wpe:
        restart: always
        build: ./wpe
        privileged: true
        ports:
        - 8080:8080
    scheduler:
        restart: always
        build: ./scheduler
        privileged: true
    wifi-connect:
        build: ./wifi-connect
        restart: always
        network_mode: host
        privileged: true
    labels:
        io.balena.features.dbus: '1'
        io.balena.features.firmware: '1'
    photos:
        privileged: true
        restart: always
        build: ./photos
        ports:
        - "8888:8888"


